-- SCRIPT PARA CRIAR O BANCO DE DADOS (NOS TESTES FOI USADO MySQL Workbench) --
CREATE SCHEMA IF NOT EXISTS `projeto_1`;

USE `projeto_1`;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `idade` INT NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `salt` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `cpf`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)
);
